### ISSUE TITLE
Docker compose YAML template

### ISSUE THREAD

**Issue by INPoppoRTUNE** [fe80Grau/ytdlp2STRM#31]
Here's a compose template based on [fe80grau/ytdlp2strm](https://hub.docker.com/r/fe80grau/ytdlp2strm) that you might want to add to your README:
```yaml
---
version: "2.1"
services:
ytdlp2strm:
    image: fe80grau/ytdlp2strm
    container_name: ytdlp2STRM
    environment:
      - AM_I_IN_A_DOCKER_CONTAINER=Yes
      - DOCKER_PORT=5005
    volumes:
      - /local/path/to/media:/media
      - /local/path/to/channel_list.json:/opt/ytdlp2STRM/plugins/youtube/channel_list.json
      - /local/path/to/yt_config.json:/opt/ytdlp2STRM/plugins/youtube/config.json
      - /local/path/to/config.json:/opt/ytdlp2STRM/config/config.json
      - /local/path/to/crons.json:/opt/ytdlp2STRM/config/crons.json
      - ytdlp2strm-data:/opt/ytdlp2STRM
    ports:
      - 5005:5000
    restart: always
volumes:
  ytdlp2strm-data:
```

Where:
- `/local/path/to/media` is the local folder where the `.strm` file will be created
- `/local/path/to/config.json` is optional and will set your ytdlp2STRM general settings; formatted as [config.example.json](https://github.com/fe80Grau/ytdlp2STRM/blob/main/config/config.example.json)
- `/local/path/to/crons.json` is optional and will set your ytdlp2STRM cronjob settings; formatted as [crons.example.json](https://github.com/fe80Grau/ytdlp2STRM/blob/main/config/crons.example.json)
- `/local/path/to/channel_list.json` is optional and will set your Youtube channel list; formatted as [channel_list.example.json](https://github.com/fe80Grau/ytdlp2STRM/blob/main/plugins/youtube/channel_list.example.json)
- `/local/path/to/yt_config.json` is optional and will set your Youtube plugin settings; formatted as [config.example.json](https://github.com/fe80Grau/ytdlp2STRM/blob/main/plugins/youtube/config.example.json)

Also I'm not sure if the environment variable `DOCKER_PORT` is still needed, can you confirm this?
Thanks again for the amazing job!
